#!/bin/bash

set -o errexit

function usage_and_die() {
    echo "$0 env-dir sso-dir [--local | --uec]"
    exit 1
}

[ "$1" ] || usage_and_die

ENV=$1; shift
SSO=$1; shift
PYPI=$1; shift || true

[ -n "$ENV" -a -n "$SSO" -a -e "$SSO" -a -z "$1" ] || usage_and_die

pypi=''
url=''
if [ "$PYPI" = '--local' ]; then
    url='http://localhost:8000'
    pypi="-i $url"
elif [ "$PYPI" = '--uec' ]; then
    url='http://10.55.56.106:8000'
    pypi="-i $url"
else
    pypi="-f https://launchpad.net/lazr.restfulclient/+download?start=9"
fi

virtualenv --distribute --no-site-packages $ENV
. $ENV/bin/activate

pushd .
cd /tmp
if [ -n "$url" ]; then
    wget -c "$url/media/dists/egenix-mx-base-3.1.3.zip"
    unzip egenix-mx-base-3.1.3.zip
else
    wget -c http://downloads.egenix.com/python/egenix-mx-base-3.1.3.tar.gz
    tar xf egenix-mx-base-3.1.3.tar.gz
fi
cd egenix-mx-base-3.1.3
python setup.py install
cd ..
rm -r egenix-mx-base-3.1.3
popd

pip install -r $SSO/requirements.txt $pypi

if  [ -z "$pypi" ]; then
    # Force lazr.restfulclient to come from the env, not from the
    # system
    pip install --no-deps lazr.restfulclient==0.9.10 $pypi
fi
pip install --no-deps lazr.restfulclient==0.9.11 $pypi

echo
echo OK
